MODEL:
  NUM_CLASSES: 2
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("gdd_train", )
  TEST: ("gdd_test", )
SOLVER:
  MAX_ITER: 150000
  LR_STEPS: [100000, 125000]
  GAMMA: 0.1
  BATCH_SIZE: 8
  LR: 1e-3

OUTPUT_DIR: 'outputs/vgg_ssd300_gdd_voc_test'